# This file was generated by GoReleaser. DO NOT EDIT.
cask "sslcheck" do
  version "0.0.2"

  on_macos do
    on_intel do
      sha256 "e39273285b278bc0b99b4060a8c8bf6432dfa62e48ce542f92ab5d9d1b774c44"
      url "https://github.com/auth-it-center/sslcheck/releases/download/v#{version}/sslcheck_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "6ad9da370fa742fc250e0d5182b75cc51d6b388b55783104f84b7ab8c97504e7"
      url "https://github.com/auth-it-center/sslcheck/releases/download/v#{version}/sslcheck_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fbe85e1299d9c0d2c85371fe6f52bf2ff54970b002be8d64ae409039692bca3e"
      url "https://github.com/auth-it-center/sslcheck/releases/download/v#{version}/sslcheck_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "6836cd450fa3371dad6b6c906f0f3904297d39f54319c23a691a0868d2e18d0f"
      url "https://github.com/auth-it-center/sslcheck/releases/download/v#{version}/sslcheck_Linux_arm64.tar.gz"
    end
  end

  name "sslcheck"
  desc "Fetch a host's TLS certificate and check it against its CRL(s)"
  homepage "https://github.com/auth-it-center/sslcheck"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sslcheck"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sslcheck"]
    end
  end

  # No zap stanza required

end
