# This file was generated by GoReleaser. DO NOT EDIT.
cask "sslcheck" do
  version "0.0.2"

  on_macos do
    on_intel do
      sha256 "2ec9b6d861fd40ae38644a70248bf4088e5b03e275e82255a3f74e7d885f6656"
      url "https://github.com/auth-it-center/sslcheck/releases/download/v#{version}/sslcheck_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ae01d85675b1de1ed67f07e7570d31ff6e5ecc3a315e74401fdce2260b64f1bc"
      url "https://github.com/auth-it-center/sslcheck/releases/download/v#{version}/sslcheck_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b67e4d8c26d80d74fc1158d1792b58cbf2c7de0b4e7924d6b3cbd1d643a332e3"
      url "https://github.com/auth-it-center/sslcheck/releases/download/v#{version}/sslcheck_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "da020d22b3daa3980b3879e6ac6e9e455e72698d7d5fef52c48dc560487e6905"
      url "https://github.com/auth-it-center/sslcheck/releases/download/v#{version}/sslcheck_Linux_arm64.tar.gz"
    end
  end

  name "sslcheck"
  desc "Fetch a host's TLS certificate and check it against its CRL(s)"
  homepage "https://github.com/auth-it-center/sslcheck"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sslcheck"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sslcheck"]
    end
  end

  # No zap stanza required

end
