# This file was generated by GoReleaser. DO NOT EDIT.
cask "sslcheck" do
  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "d160033d4d73eedaef7828dc70d1622774b867ce864659e5aeb940d2a8832a96"
      url "https://github.com/auth-it-center/sslcheck/releases/download/v#{version}/sslcheck_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "e56c7bd477fed59b1a4f93da1958ee86dab2fa674da1d226eaadb97764d6cdc4"
      url "https://github.com/auth-it-center/sslcheck/releases/download/v#{version}/sslcheck_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b9fa970caeffa74896cff43688c9e96c800bc6ead902a27854ea7a018bafb9f2"
      url "https://github.com/auth-it-center/sslcheck/releases/download/v#{version}/sslcheck_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "26f69bc7c1215b12298a7d78c9565dbde7ff3534fffdccde09f103b773a73947"
      url "https://github.com/auth-it-center/sslcheck/releases/download/v#{version}/sslcheck_Linux_arm64.tar.gz"
    end
  end

  name "sslcheck"
  desc "Fetch a host's TLS certificate and check it against its CRL(s)"
  homepage "https://github.com/auth-it-center/sslcheck"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sslcheck"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sslcheck"]
    end
  end

  # No zap stanza required

end
